// Code generated by hertz generator.

package lottery

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/util"
)

// GeneralLotteryList @Summary 抽卡记录查询
// @Description 抽卡记录查询
// @Tags 模拟抽卡
// @Accept json
// @Produce json
// @Router /v1/lottery/general/list [GET]
func GeneralLotteryList(ctx context.Context, c *app.RequestContext) {
	var resp api.GeneralLotteryListResponse
	resp.Meta = util.BuildSuccMeta()

	//todo

	hlog.CtxInfof(ctx, "GeneralLotteryList Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}
