// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"github.com/keycasiter/3g_game/biz/conf"
	"github.com/keycasiter/3g_game/biz/dal/cache"
	"github.com/keycasiter/3g_game/biz/dal/mysql"
	"github.com/keycasiter/3g_game/biz/dal/redis"
	"time"
)

func main() {
	h := server.Default(server.WithHostPorts("0.0.0.0:80"))

	//跨域配置
	h.Use(cors.New(cors.Config{

		//准许跨域请求网站,多个使用,分开,限制使用*
		AllowOrigins: []string{"*"},
		//准许使用的请求方式
		AllowMethods: []string{
			"PUT", "PATCH", "POST", "GET", "DELETE"},
		//准许使用的请求表头
		AllowHeaders: []string{
			"Origin", "Authorization", "Content-Type"},
		//显示的请求表头
		ExposeHeaders: []string{
			"Content-Type"},
		//凭证共享,确定共享
		AllowCredentials: true,
		//容许跨域的原点网站,可以直接return true就万事大吉了
		AllowOriginFunc: func(origin string) bool {
			return true
		},
		//超时时间设定
		MaxAge: 24 * time.Hour,
	}))

	//***init***
	//初始化配置文件
	conf.InitConfig()
	//初始化mysql
	mysql.InitMysql()
	//初始化redis
	redis.InitRedis()
	//初始化Cache
	cache.InitCache()

	register(h)
	h.Spin()
}
