// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
)

func main() {
	h := server.Default()
	register(h)
	h.Spin()

	//日志
	logger := hertzlogrus.NewLogger()
	hlog.SetLogger(logger)
}
