// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/keycasiter/3g_game/biz/logic"
	"github.com/keycasiter/3g_game/biz/util"

	"github.com/cloudwego/hertz/pkg/app"
	api "github.com/keycasiter/3g_game/biz/model/api"
)

// MetadataGeneralPageableList .
// @router /v1/resource/general/pageable_list [GET]
func MetadataGeneralPageableList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MetadataGeneralPageableListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	list, err := logic.NewMetadataGeneralLogic(ctx, req).MetadataGeneralPageableList()
	if err != nil {
		hlog.CtxErrorf(ctx, "MetadataGeneralPageableList err:%v", err)
		c.String(400, err.Error())
		return
	}

	resp := &api.MetadataGeneralPageableListResponse{
		Meta: util.BuildSuccMeta(),
		Data: list,
	}

	c.JSON(200, resp)
}
