// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/keycasiter/3g_game/biz/consts"
	"github.com/keycasiter/3g_game/biz/logic"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/model/vo"
	"github.com/keycasiter/3g_game/biz/util"
)

// GeneralLottery .
// @router /v1/lottery/general [POST]
func GeneralLottery(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GeneralLotteryRequest
	var resp api.GeneralLotteryResponse
	resp.Meta = util.BuildSuccMeta()

	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}
	if req.Uid == "" || req.RollTimes == 0 || req.GeneralLotteryPool == 0 {
		hlog.CtxErrorf(ctx, "GeneralLottery param err")
		resp.Meta = util.BuildParamErrMeta()
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	hlog.CtxInfof(ctx, "GeneralLottery Req:%s", util.ToJsonString(ctx, req))

	logicResp, err := logic.NewGeneralLotteryLogic(ctx, &vo.GeneralLotteryRequest{
		GeneralLottery: consts.GeneralLotteryPool(req.GeneralLotteryPool),
		RollTimes:      req.RollTimes,
		Uid:            req.Uid,
	}).Run()
	if err != nil {
		hlog.CtxErrorf(ctx, "GeneralLotteryLogic handle err:%v", err)
		resp.Meta = util.BuildFailMetaWithMsg(err.Error())
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	//组合resp
	generalLotteryInfoList := make([]*api.GeneralLotteryInfo, 0)
	for _, info := range logicResp.GeneralLotteryInfoList {
		generalLotteryInfoList = append(generalLotteryInfoList, &api.GeneralLotteryInfo{
			GeneralInfo: &api.MetadataGeneral{
				Id:   info.GeneralInfo.Id,
				Name: info.GeneralInfo.Name,
			},
			HitNum:      info.HitNum,
			HitRate:     info.HitRate,
			LotteryRate: info.LotteryRate,
		})
	}

	resp.Hit5LevGeneralNum = logicResp.Hit5LevGeneralNum
	resp.ProtectedMustHitNum = logicResp.ProtectedMustHitNum
	resp.GeneralLotteryInfoList = generalLotteryInfoList

	hlog.CtxInfof(ctx, "GeneralLottery Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}
