// Code generated by hertz generator.

package api

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/keycasiter/3g_game/biz/consts"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/model/enum"
	"github.com/keycasiter/3g_game/biz/model/po"
	"github.com/keycasiter/3g_game/biz/util"
)

// GeneralLotteryInfoList @Summary 卡池武将查询
// @Description 卡池武将查询
// @Tags 模拟抽卡
// @Accept json
// @Produce json
// @Router /v1/lottery/general/info_query [GET]
func GeneralLotteryInfoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GeneralLotteryInfoListRequest
	var resp api.GeneralLotteryInfoListResponse
	resp.Meta = util.BuildSuccMeta()

	err = c.BindAndValidate(&req)
	hlog.CtxInfof(ctx, "GeneralLotteryInfoList Req:%s", util.ToJsonString(ctx, req))
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}
	if req.GeneralLotteryPool == 0 {
		resp.Meta = util.BuildParamErrMeta()
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	//组合resp
	generalLotteryInfoList := make([]*api.GeneralLotterInfoQueryInfo, 0)
	generalInfos := make([]*api.MetadataGeneral, 0)
	generalPool := consts.GeneralLotteryPool(req.GeneralLotteryPool)
	if generalMap, ok := consts.GeneralLotteryPoolMap[generalPool]; ok {
		for generalId, _ := range generalMap {
			var general *po.General
			generalInfos = append(generalInfos, &api.MetadataGeneral{
				Id:             int64(generalId),
				Name:           general.Name,
				GeneralQuality: enum.GeneralQuality(general.Quality),
				AvatarUrl:      general.AvatarUrl,
			})
		}
		generalLotteryInfoList = append(generalLotteryInfoList, &api.GeneralLotterInfoQueryInfo{
			GeneralInfoList:        generalInfos,
			GeneralLotteryPool:     int64(generalPool),
			GeneralLotteryPoolName: fmt.Sprintf("%v", generalPool),
		})
	}
	resp.GeneralLotteryPoolInfoList = generalLotteryInfoList

	hlog.CtxInfof(ctx, "GeneralLotteryInfoList Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}
