// Code generated by hertz generator.

package api

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/keycasiter/3g_game/biz/consts"
	"github.com/keycasiter/3g_game/biz/dal/cache"
	"github.com/keycasiter/3g_game/biz/logic"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/model/enum"
	"github.com/keycasiter/3g_game/biz/model/po"
	"github.com/keycasiter/3g_game/biz/model/vo"
	"github.com/keycasiter/3g_game/biz/util"
)

// GeneralLotteryDo .
// @router /v1/lottery/general/do [POST]
func GeneralLotteryDo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GeneralLotteryDoRequest
	var resp api.GeneralLotteryDoResponse
	resp.Meta = util.BuildSuccMeta()

	err = c.BindAndValidate(&req)
	hlog.CtxInfof(ctx, "GeneralLotteryDo Req:%s", util.ToJsonString(ctx, req))
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}
	if req.Uid == "" || req.RollTimes == 0 || req.GeneralLotteryPool == 0 {
		hlog.CtxErrorf(ctx, "GeneralLotteryDo param err")
		resp.Meta = util.BuildParamErrMeta()
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	logicResp, err := logic.NewGeneralLotteryLogic(ctx, &vo.GeneralLotteryRequest{
		GeneralLottery: consts.GeneralLotteryPool(req.GeneralLotteryPool),
		RollTimes:      req.RollTimes,
		Uid:            req.Uid,
	}).Run()
	if err != nil {
		hlog.CtxErrorf(ctx, "GeneralLotteryDoLogic handle err:%v", err)
		resp.Meta = util.BuildFailMetaWithMsg(err.Error())
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	//组合resp
	generalLotteryInfoList := make([]*api.GeneralLotteryDoInfo, 0)
	for _, info := range logicResp.GeneralLotteryInfoList {
		generalLotteryInfoList = append(generalLotteryInfoList, &api.GeneralLotteryDoInfo{
			GeneralInfo: &api.MetadataGeneral{
				Id:             info.GeneralInfo.Id,
				Name:           info.GeneralInfo.Name,
				GeneralQuality: enum.GeneralQuality(info.GeneralInfo.Quality),
			},
			HitNum:      info.HitNum,
			HitRate:     info.HitRate,
			LotteryRate: info.LotteryRate,
		})
	}

	resp.Hit5LevGeneralNum = logicResp.Hit5LevGeneralNum
	resp.ProtectedMustHitNum = logicResp.ProtectedMustHitNum
	resp.GeneralLotteryInfoList = generalLotteryInfoList

	hlog.CtxInfof(ctx, "GeneralLotteryDo Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}

// GeneralLotteryQuery .
// @router /v1/lottery/general/query [GET]
func GeneralLotteryQuery(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GeneralLotteryQueryRequest
	var resp api.GeneralLotteryQueryResponse
	resp.Meta = util.BuildSuccMeta()

	err = c.BindAndValidate(&req)
	hlog.CtxInfof(ctx, "GeneralLotteryQuery Req:%s", util.ToJsonString(ctx, req))
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}

	//组合resp
	generalLotteryInfoList := make([]*api.GeneralLotteryQueryInfo, 0)
	generalInfos := make([]*api.MetadataGeneral, 0)
	for _, lotteryPoolId := range consts.GeneralLotteryPoolArr {
		if generalMap, ok := consts.GeneralLotteryPoolMap[lotteryPoolId]; ok {
			for generalId, _ := range generalMap {
				var general *po.General
				//从缓存获取
				if vo, okk := cache.CacheGeneralMap[int64(generalId)]; okk {
					general = vo
				}
				generalInfos = append(generalInfos, &api.MetadataGeneral{
					Id:   int64(generalId),
					Name: general.Name,
				})
			}
		}

		generalLotteryInfoList = append(generalLotteryInfoList, &api.GeneralLotteryQueryInfo{
			GeneralInfoList:        generalInfos,
			GeneralLotteryPool:     int64(lotteryPoolId),
			GeneralLotteryPoolName: fmt.Sprintf("%v", lotteryPoolId),
		})
	}
	resp.GeneralLotteryInfoList = generalLotteryInfoList

	hlog.CtxInfof(ctx, "GeneralLottery Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}
