// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/keycasiter/3g_game/biz/logic/common"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/util"
)

// CommonNotice @Summary 查询公告列表
// @Description 查询公告列表
// @Tags 通用
// @Accept json
// @Produce json
// @Router /v1/common/notice [GET]
func CommonNotice(ctx context.Context, c *app.RequestContext) {
	var err error
	var req *api.CommonNoticeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}

	hlog.CtxInfof(ctx, "CommonNotice Req:%s", util.ToJsonString(ctx, req))

	resp, err := common.NewCommonNoticeLogic(ctx, req).Run()
	if err != nil {
		hlog.CtxErrorf(ctx, "CommonNotice handle err:%v", err)
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	hlog.CtxInfof(ctx, "CommonNotice Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}
