// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/keycasiter/3g_game/biz/logic"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/util"
)

// SpecialTechQuery .
// @router /v1/rec_team/query [GET]
func RecTeamQuery(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RecTeamQueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}

	hlog.CtxInfof(ctx, "RecTeamQuery Req:%s", util.ToJsonString(ctx, req))

	resp, err := logic.NewRecTeamQueryLogic(ctx, req).Handle()
	if err != nil {
		hlog.CtxErrorf(ctx, "RecTeamQueryLogic handle err:%v", err)
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	hlog.CtxInfof(ctx, "RecTeamQuery Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}
