// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/keycasiter/3g_game/biz/logic/battle"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/util"
)

// RecTeamList @Summary 查询推荐阵容
// @Description 查询推荐阵容
// @Tags 模拟对战
// @Accept json
// @Produce json
// @Router /v1/rec_team/list [GET]
func RecTeamList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RecTeamListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}

	hlog.CtxInfof(ctx, "RecTeamList Req:%s", util.ToJsonString(ctx, req))

	resp, err := battle.NewRecTeamListLogic(ctx, req).Handle()
	if err != nil {
		hlog.CtxErrorf(ctx, "RecTeamListLogic handle err:%v", err)
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	hlog.CtxInfof(ctx, "RecTeamList Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}
