// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/util"
)

// RecTacticList @Summary 查询推荐阵容
// @Description 查询推荐阵容
// @Tags 模拟对战
// @Accept json
// @Produce json
// @Router /v1/rec_team/list [GET]
func RecTacticList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RecTacticListRequest
	var resp api.RecTacticListResponse
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}

	hlog.CtxInfof(ctx, "RecTacticList Req:%s", util.ToJsonString(ctx, req))

	hlog.CtxInfof(ctx, "RecTacticList Resp length:%v", len(resp.RecTacticList))

	c.JSON(hertzconsts.StatusOK, resp)
}
