// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/keycasiter/3g_game/biz/model/api"
)

// SpecialTechQuery .
// @router /v1/special_tech/query [GET]
func SpecialTechQuery(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SpecialTechQueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.SpecialTechQueryResponse)

	c.JSON(hertzconsts.StatusOK, resp)
}
