// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/keycasiter/3g_game/biz/logic"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/util"
)

// SpecialTechQuery .
// @router /v1/special_tech/query [GET]
func SpecialTechQuery(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SpecialTechQueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}

	hlog.CtxInfof(ctx, "SpecialTechQuery Req:%s", util.ToJsonString(ctx, req))

	resp, err := logic.NewSpecialTechQueryLogic(ctx, req).Handle()
	if err != nil {
		hlog.CtxErrorf(ctx, "SpecialTechQueryLogic handle err:%v", err)
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	hlog.CtxInfof(ctx, "SpecialTechQuery Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}
