// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generalMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _metadatageneralpageablelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _battleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _battleexecuteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generalqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _special_techMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _specialtechqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tacticMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tacticqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _warbookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _warbookqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _general_warbookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generalwarbookqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rec_teamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recteamqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserwxopenidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _lotteryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotteryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _general0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotterydoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotteryqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _general_rateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotteryratequeryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotteryinfoqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotterypoolqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotterydataresetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotterydataqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotteryuserdataqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotteryuserdataresetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generallotterypoolinfoqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _jymMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _accountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _accountsearchMw() []app.HandlerFunc {
	// your code...
	return nil
}
