// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generalMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _metadatageneralpageablelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _battleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _battleexecuteMw() []app.HandlerFunc {
	// your code...
	return nil
}
