Mysql:
  User: "root"
  Password: "root123!@#"
  Host: "127.0.0.1"
  Port: "3306"
  DbName: "3g_game"

Redis:

Mongodb:
  Uri: "mongodb://127.0.0.1:27017/3g_game"
  Database: "3g_game"
  ConnectTimeout: 3