Mysql:
  User: "root"
  Password: "root123!@#"
  Host: "127.0.0.1"
  Port: "3306"
  DbName: "3g_game"

Redis:
  Addr: "59.110.5.63:6379"
  Password: "root123!@#"
  DB: "0"

Mongodb:
  Uri: "mongodb://127.0.0.1:27017/3g_game"
  Database: "3g_game"
  ConnectTimeout: 3

Wexin:
  AppId: "wx7a3c08a1bc4de9a3"
  Secret: "66ea53ce2bc5a01d9acf1c3d740a660b"