Mysql:
  User: "root"
  Password: "gj+9012-"
  Host: "59.110.5.63"
  Port: "3306"
  DbName: "3game"

Redis:

Mongodb:
  Uri: "mongodb://admin:123456@127.0.0.1:27017/3g_game"
  Database: "3g_game"
  ConnectTimeout: 3