Mysql:
  User: "root"
  Password: "gj+9012-"
  Host: "59.110.5.63"
  Port: "3306"
  DbName: "3game"

Redis:
  Addr: "59.110.5.63:6379"
  Password: "root123!@#"
  DB: "0"

Mongodb:
  Uri: "mongodb://admin:123456@127.0.0.1:27017/3g_game"
  Database: "3g_game"
  ConnectTimeout: 3

Wexin:
  AppId: "wx6d8a318f20ba48f1"
  Secret: "24195480c108ffbb965c47770000774f"
  GetUserOpenIdApiTemplateUrl : "https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code"

Neo4j:
  DbUri: "localhost:7687"
  UserName: "neo4j"
  Password: "root123!@#"