// Code generated by hertz generator.

package battle

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzconsts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/keycasiter/3g_game/biz/logic/battle"
	api "github.com/keycasiter/3g_game/biz/model/api"
	"github.com/keycasiter/3g_game/biz/util"
)

// SpecialTechList @Summary 查询特技列表
// @Description 查询特技列表
// @Tags 模拟对战
// @Accept json
// @Produce json
// @Router /v1/special_tech/list [GET]
func SpecialTechList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SpecialTechListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(hertzconsts.StatusBadRequest, err.Error())
		return
	}

	hlog.CtxInfof(ctx, "SpecialTechList Req:%s", util.ToJsonString(ctx, req))

	resp, err := battle.NewSpecialTechListLogic(ctx, req).Handle()
	if err != nil {
		hlog.CtxErrorf(ctx, "SpecialTechListLogic handle err:%v", err)
		c.JSON(hertzconsts.StatusOK, resp)
		return
	}

	hlog.CtxInfof(ctx, "SpecialTechList Resp:%s", util.ToJsonString(ctx, resp))

	c.JSON(hertzconsts.StatusOK, resp)
}
