package consts

type TacticId int64

const (
	//鹰视狼顾
	ClearEyedAndMalicious TacticId = iota + 1
	//士别三日
	ThreeDaysOfSeparation
	//熯天炽地
	TheSkyIsBlazing
	//乱世奸雄
	TraitorInTroubledTimes
	//盛气凌敌
	OverwhelmingTheEnemyWithVigour
	//挫锐
	Demoralize
	//守而必固
	ToKeepAndBeFirm
	//横戈跃马
	Gallant
	//暂避其锋
	TakeRefugeFromEnemies
	//魅惑
	Charming
	//抚揖军民
	AppeaseArmyAndPeople
	//镇扼防拒
	SuppressChokesAndPreventRefusals
	//锋矢阵
	FrontalVectorArray
	//刮骨疗毒
	Curettage
	//义胆雄心
	BraveAmbition
	//夺魂挟魄
	SeizeTheSoul
	//火炽原燎
	BlazingWildfire
	//连环计
	InterlockedStratagems
	//太平道法
	TaipingLaw
	//无当飞军
	WuDangFlyArmy
	//神机妙算
	CleverStrategyAndShrewdTactics
	//八门金锁阵
	EightGateGoldenLockArray
	//草船借箭
	BorrowArrowsWithThatchedBoats
	//长者之风
	TheWindOfTheElderly
	//偃旗息鼓
	LowerBannersAndMuffleDrums
	//出其不意
	TakeBySurprise
	//庐江上甲
	LuJiangRiverOverArmoured
	//矢志不移
	OnesResolveIsUnshaken
	//所向披靡
	EverTriumphant
	//盛气凌敌
	OvercomingTheEnemyWithGreatEnergy
	//破阵摧坚
	BreakingThroughTheFormationAndDestroyingTheFirm
	//杯蛇鬼车
	CupSnakeGhostCar
	//四面楚歌
	BeBesiegedOnAllSides
	//瞋目横矛
	AngryEyeHorizontalSpear
	//暴戾无仁
	ViolentAndHeartless
	//沉沙决水
	SinkingSandAndBreakingWater
	//诱敌深入
	LureTheEnemyInDeep
	//一骑当千
	IkkiTousen
	//乘敌不虞
	RidingTheEnemyWithoutFear
	//百骑劫营
	HundredCavalryRobberyBattalions
	//折冲御侮
	RepelForeignAggression
	//合军聚众
	GatheringOfTroops
	//克敌制胜
	VanquishTheEnemy
	//兵锋
	TheSharpnessOfMilitaryStrength
	//风助火势
	WindAssistedFire
	//智计
	IntelligentStrategy
	//勇者得前
	TheBraveLeadTheWay
	//白马义从
	WhiteHorseFollowsWithLoyalty
	//文武双全
	BeAdeptWithBothThePenAndTheSword
	//兵无常势
	WorkOutMeasuresToSuitLocalConditions
	//藤甲兵
	TengjiaSoldier
	//陷阵营
	FallIntoCamp
	//西凉铁骑
	XiLiangIronCavalry
	//虎豹骑
	TigerAndLeopardCavalry
	//白毦兵
	WhiteArmy
	//横扫千军
	SweepAwayTheMillionsOfEnemyTroops
	//用武通神
	UseMartialArtsToConnectWithGods
	//绝地反击
	JediCounterattack
	//梦中弑臣
	KillingMinisterInDream
	//伪书相间
	FakeBooksAlternateWithEachOther
	//奇计良谋
	CleverPlanAndCleverPlan
	//万箭齐发
	TenThousandArrowsShotAtOnce
	//舌战群儒
	LectureField
	//大戟士
	GreatHalberdWarrior
	//义心昭烈
	TheHeartOfRighteousnessShines
	//卧薪尝胆
	SleepOnTheBrushwoodAndTasteTheGall
	//倾国倾城
	BeautyWhichOverthrowsStatesAndCities
	//象兵
	ElephantSoldier
	//虎卫军
	TigerGuardArmy
	//锦帆军
	JinFanArmy
	//青州兵
	QingZhouSoldier
	//乘胜长驱
	RidingOnTheVictoryDrive
	//一力拒守
	RefuseToDefendWithOneForce
	//运筹决算
	DecisionMakingThroughOperationsResearch
	//铁骑驱驰
	IronHorseDrive
	//形机军略
	MilitaryStrategyForFormAircraft
	//箕形阵
	DustpanFormation
	//焰逐风飞
	FlamesFlyingInTheWind
	//威谋靡亢
	IntenseAndPowerful
	//破军威胜
	BreakingThroughTheArmyAndWinningVictories
	//速乘其利
	TakeAdvantageOfQuickly
	//士争先赴
	ScholarsStriveToGoFirst
	//先成其虑
	TakeCareOfYourselfFirst
	//竭力佐谋
	MakeEveryEffortToAssistInPlanning
	//临机制胜
	SeizeTheOpportunityToWin
	//忠勇义烈
	LoyalAndBraveMartyrs
	//气凌三军
	TemperamentSurpassesTheThreeArmies
	//鬼神霆威
	GhostGodThunderForce
	//焚辎营垒
	ToBurnBarracks
	//虎踞鹰扬
	TigerCrouchingAndEagleSoaring
	//三势阵
	ThreePotentialArray
	//当锋摧决
	WhenTheFrontIsDestroyed
	//刚勇无前
	StrongAndBraveWithoutAdvance
	//引弦力战
	LeadStringBattle
	//血刃争锋
	BloodBladeBattle
	//决水溃城
	BreakingThroughTheWaterAndCrushingTheCity
	//裸衣血战
	NakedBloodBattle
	//婴城自守
	InfantryCitySelfDefense
	//独行赴斗
	TravelingAloneToFight
	//据水断桥
	BrokenBridgeByWater
	//武锋阵
	WuFengArray
	//绝其汲道
	EliminateItAndDrawFromIt
	//击其惰归
	StrikeItsLazyReturn
	//千里走单骑
	ThousandMileWalkingSingleRider
	//形一阵
	ShapelyArray
	//潜龙阵
	HiddenDragonArray
	//掣刀斫敌
	PullingSwordsAndChoppingEnemies
	//强攻
	TakeByStorm
	//净化
	Purify
	//驱散
	Disperse
	//挟势弄权
	TakingAdvantageOfTheSituationToGainPower
	//传檄宣威
	ToSpreadRumorsAndProclaimPower
	//整装待发
	BeFullyEquippedFor
	//敛众而击
	GatherTheCrowdAndStrike
	//妖术
	BlackArt
	//一举歼灭
	AnnihilateInOneFellSwoop
	//不辱使命
	HaveSucceededInCarryingOutAnAssignment
	//暗藏玄机
	HiddenMystery
	//诈降
	PretendToSurrender
	//屠几上肉
	SlaughterMeatOnTable
	//左右开弓
	DrawTheBowBothOnTheLeftAndRight
	//骁勇善战
	BraveAndBattlewise
	//御敌屏障
	DefensiveBarrier
	//料事如神
	ForetellLikeProphet
	//挫志怒袭
	FrustrationAndAngerAttack
	//避实击虚
	AvoidTheSolidAndStrikeTheWeak
	//奋突
	RiseUpBravely
	//骑虎难下
	RideTigerAndFindItHardToGetOff
	//弯弓饮羽
	BendTheBowAndDrinkTheFeathers
	//落凤
	FallingPhoenix
	//落雷
	Thunderbolt
	//声东击西
	MakeFeintToTheEastButAttackInTheWest
	//风声鹤唳
	TheSoundOfTheWindAndTheCryOfTheStork
	//天降火雨
	RainOfFireFromTheSky
	//手起刀落
	CutDown
	//后发制人
	GainMasteryByStrikingOnlyAfterTheEnemyHasStruck
	//白眉
	EyebrowedThrush
	//千里驰援
	ThousandsOfMilesOfSupport
	//坐守孤城
	SittingInAnIsolatedCity
	//轻勇飞燕
	FearlessAndBraveFlyingSwallow
	//纵兵劫掠
	LeavingSoldiersToPlunder
	//唇枪舌战
	HaveVerbalBattleWithSomebody
	//机略纵横
	MachineStrategyVerticalAndHorizontal
	//自愈
	SelfHealing
	//暴敛四方
	OverwhelmingAllDirections
	//斗智
	BattleOfWits
	//包扎
	Dress
	//挑衅
	Provoke
	//横扫
	SweepAway
	//追伤
	ChasingInjury
)
