package consts

type TacticId int64

const (
	//鹰视狼顾
	ClearEyedAndMalicious TacticId = iota + 1
	//士别三日
	ThreeDaysOfSeparation
	//熯天炽地
	TheSkyIsBlazing
	//乱世奸雄
	TraitorInTroubledTimes
	//盛气凌敌
	OverwhelmingTheEnemyWithVigour
	//挫锐
	Demoralize
	//守而必固
	ToKeepAndBeFirm
	//横戈跃马
	Gallant
	//暂避其锋
	TakeRefugeFromEnemies
	//魅惑
	Charming
	//抚揖军民
	AppeaseArmyAndPeople
	//镇扼防拒
	SuppressChokesAndPreventRefusals
	//锋矢阵
	FrontalVectorArray
	//刮骨疗毒
	Curettage
	//义胆雄心
	BraveAmbition
	//夺魂挟魄
	SeizeTheSoul
	//火炽原燎
	BlazingWildfire
	//连环计
	InterlockedStratagems
	//太平道法
	TaipingLaw
	//无当飞军
	WuDangFlyArmy
	//神机妙算
	CleverStrategyAndShrewdTactics
	//八门金锁阵
	EightGateGoldenLockArray
	//草船借箭
	BorrowArrowsWithThatchedBoats
	//长者之风
	TheWindOfTheElderly
	//偃旗息鼓
	LowerBannersAndMuffleDrums
	//出其不意
	TakeBySurprise
	//庐江上甲
	LuJiangRiverOverArmoured
	//矢志不移
	OnesResolveIsUnshaken
	//所向披靡
	EverTriumphant
	//盛气凌敌
	OvercomingTheEnemyWithGreatEnergy
	//破阵摧坚
	BreakingThroughTheFormationAndDestroyingTheFirm
	//杯蛇鬼车
	CupSnakeGhostCar
	//四面楚歌
	BeBesiegedOnAllSides
	//瞋目横矛
	AngryEyeHorizontalSpear
	//暴戾无仁
	ViolentAndHeartless
	//沉沙决水
	SinkingSandAndBreakingWater
	//诱敌深入
	LureTheEnemyInDeep
	//一骑当千
	IkkiTousen
	//乘敌不虞
	RidingTheEnemyWithoutFear
	//百骑劫营
	HundredCavalryRobberyBattalions
	//折冲御侮
	RepelForeignAggression
	//合军聚众
	GatheringOfTroops
	//守而必固
	DefendAndBeFirm
	//克敌制胜
	VanquishTheEnemy
	//兵锋
	TheSharpnessOfMilitaryStrength
	//风助火势
	WindAssistedFire
	//智计
	IntelligentStrategy
	//勇者得前
	TheBraveLeadTheWay
	//白马义从
	WhiteHorseFollowsWithLoyalty
	//文武双全
	BeAdeptWithBothThePenAndTheSword
	//兵无常势
	WorkOutMeasuresToSuitLocalConditions
	//藤甲兵
	TengjiaSoldier
	//陷阵营
	FallIntoCamp
	//西凉铁骑
	XiLiangIronCavalry
	//虎豹骑
	TigerAndLeopardCavalry
	//白毦兵
	WhiteArmy
	//横扫千军
	SweepAwayTheMillionsOfEnemyTroops
	//用武通神
	UseMartialArtsToConnectWithGods
	//绝地反击
	JediCounterattack
	//梦中弑臣
	KillingMinisterInDream
	//伪书相间
	FakeBooksAlternateWithEachOther
	//奇计良谋
	CleverPlanAndCleverPlan
	//万箭齐发
	TenThousandArrowsShotAtOnce
	//舌战群儒
	LectureField
	//大戟士
	GreatHalberdWarrior
	//义心昭烈
	TheHeartOfRighteousnessShines
	//卧薪尝胆
	SleepOnTheBrushwoodAndTasteTheGall
	//倾国倾城
	BeautyWhichOverthrowsStatesAndCities
	//象兵
	ElephantSoldier
	//虎卫军
	TigerGuardArmy
	//锦帆军
	JinFanArmy
	//青州兵
	QingZhouSoldier
	//乘胜长驱
	RidingOnTheVictoryDrive
	//一力拒守
	RefuseToDefendWithOneForce
	//运筹决算
	DecisionMakingThroughOperationsResearch
	//铁骑驱驰
	IronHorseDrive
	//形机军略
	MilitaryStrategyForFormAircraft
	//箕形阵
	DustpanFormation
	//焰逐风飞
	FlamesFlyingInTheWind
	//威谋靡亢
	IntenseAndPowerful
	//破军威胜
	BreakingThroughTheArmyAndWinningVictories
	//速乘其利
	TakeAdvantageOfQuickly
	//士争先赴
	ScholarsStriveToGoFirst
	//先成其虑
	TakeCareOfYourselfFirst
	//竭力佐谋
	MakeEveryEffortToAssistInPlanning
	//临机制胜
	SeizeTheOpportunityToWin
	//忠勇义烈
	LoyalAndBraveMartyrs
	//气凌三军
	TemperamentSurpassesTheThreeArmies
	//鬼神霆威
	GhostGodThunderForce
	//焚辎营垒
)
